db:
  name:
    - appDatabase
  url:
    - mongodb://127.0.0.1:27017
  # url:
  #   - mongodb://192.168.16.142:27017
  #   - mongodb://192.168.19.67:27017

configserivce:
  - http://127.0.0.1:3001/layout/current
